language: node_js

cache:
  directories:
  - node_modules
  - yarn

script: yarn build

deploy:
  defaults: &defaults  
    edge: true
    skip_cleanup: true
    provider: cloudfoundry
    api: https://api.ng.bluemix.net
    username: apikey
    password: ${PASSWORD}
    organization: simonfin@ie.ibm.com
    space: studios-dublin

  - "<<": defaults
    on:
      branch: dev

  - "<<": defaults
    on:
      branch: master
