group: bluezone
language: node_js

node_js:
  - 'node'

cache:
  directories:
  - node_modules

before_install:
- npm i -g makeshift && makeshift -s @ibm -r https://npm-registry.whitewater.ibm.com

script: npm run build

deploy:
  - edge: true
    skip_cleanup: true
    api: https://api.ng.bluemix.net
    provider: cloudfoundry
    username: SIMONFIN@ie.ibm.com
    password: ${PASSWORD}
    organization: simonfin@ie.ibm.com
    space: security
    manifest: manifest.yml
    on:
      branch: dev

  - edge: true
    skip_cleanup: true
    api: https://api.ng.bluemix.net
    provider: cloudfoundry
    username: SIMONFIN@ie.ibm.com
    password: ${PASSWORD}
    organization: simonfin@ie.ibm.com
    space: security
    manifest: production-manifest.yml
    on:
      branch: master
