language: node_js

cache:
  directories:
  - node_modules
  - yarn

before_deploy: yarn build

deploy:
- edge: true
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: apikey
  password: ${PASSWORD}
  organization: simonfin@ie.ibm.com
  space: studios-dublin
  on:
    all_branches: true

