language: node_js

cache:
  directories:
  - node_modules
  - yarn

script: yarn build

_template: &_template
  edge: true
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: apikey
  password: ${PASSWORD}
  organization: simonfin@ie.ibm.com
  space: studios-dublin

deploy:

  - <<: *_template
    on:
      branch: dev

  - <<: *_template
    on:
      branch: master
