language: node_js

cache:
  directories:
  - node_modules

script: npm run build

deploy:

  - edge: true
    skip_cleanup: true
    api: https://api.ng.bluemix.net
    provider: cloudfoundry
    username: SIMONFIN@ie.ibm.com
    password: ${PASSWORD}
    organization: simonfin@ie.ibm.com
    space: offset
    manifest: manifest/dev.yml
    on:
      branch: dev

  - edge: true
    skip_cleanup: true
    api: https://api.ng.bluemix.net
    provider: cloudfoundry
    username: SIMONFIN@ie.ibm.com
    password: ${PASSWORD}
    organization: simonfin@ie.ibm.com
    space: offset
    manifest: manifest/master.yml
    on:
      branch: master
