language: node_js

cache:
  directories:
  - node_modules
  - yarn

script: yarn build

_deploy: &_deploy
  edge: true
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: apikey
  password: ${PASSWORD}
  organization: simonfin@ie.ibm.com
  space: studios-dublin

deploy:
  - <<: *_deploy
    on:
      branch: dev

  - <<: *_deploy
    on:
      branch: master
