language: node_js

cache:
  directories:
  - node_modules
  - yarn

script: yarn build

deploy:

  - edge: true
    skip_cleanup: true
    api: https://api.ng.bluemix.net
    provider: cloudfoundry
    username: apikey
    password: ${PASSWORD}
    organization: simonfin@ie.ibm.com
    space: studios-dublin
    on:
      branch: dev

  - edge: true
    skip_cleanup: true
    api: https://api.ng.bluemix.net
    provider: cloudfoundry
    username: apikey
    password: ${PASSWORD}
    organization: simonfin@ie.ibm.com
    space: studios-dublin
    on:
      branch: master
