group: bluezone
language: node_js

node_js:
  - 'node'

cache:
  directories:
  - node_modules

before_install:
  - npm i -g makeshift
  - makeshift -s @ibm -r https://npm-registry.whitewater.ibm.com

script: npm run build

deploy:

  - edge: true
    skip_cleanup: true
    api: https://api.bluemix.net
    provider: cloudfoundry
    username: SIMONFIN@ie.ibm.com
    password: ${PASSWORD}
    organization: IBMSecurity
    space: sxsw-2017
    manifest: manifest.yml
    on:
      branch: dev

  - edge: true
    skip_cleanup: true
    api: https://api.bluemix.net
    provider: cloudfoundry
    username: SIMONFIN@ie.ibm.com
    password: ${PASSWORD}
    organization: IBMSecurity
    space: sxsw-2017
    manifest: production-manifest.yml
    on:
      branch: master
